name: servis_denetim_app
description: "Okul Servis Araçları Denetim Sistemi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.1.2
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  provider: ^6.0.5
  printing: ^5.11.2
  pdf: ^3.11.3
  intl: ^0.18.1
  file_picker: ^8.1.2
  open_file: ^3.3.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/  # Font dosyalarınızın olduğu klasör
  fonts:
    - family: DejaVuSans
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf  # assets/ eklenmeli